//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YokyoTestapp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BroadCastDetailTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BroadCastDetailTable()
        {
            this.BookingTable = new HashSet<BookingTable>();
        }
    
        public int DetailId { get; set; }
        public string GameType { get; set; }
        public string GameName { get; set; }
        public Nullable<System.DateTime> BroadCastDate { get; set; }
        public string Remarks { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BookingTable> BookingTable { get; set; }
    }
}
